# Reusable Workflow Scenario
#  Passing down environment as input variable to 
#  Test for https://github.com/github/customer-feedback/issues/5627
name: RWF Caller Passing environment as input

on:
  workflow_dispatch:

jobs:
  Caller:
    uses: gateixeira-demo-org/reusable-workflows/.github/workflows/reusable-secrets.yml@main
    with:
      runson: ubuntu-latest
      env: prod
    secrets: inherit
